import React, { } from "react";
import { Button, Col, ProgressBar, Row, Stack } from "react-bootstrap";
import { useNavigate } from "react-router-dom";
import "bootstrap/dist/css/bootstrap.min.css";
import BarChart from "../Chart/BarChart";
import '../../screens/ClientManager/leads.css';
const Leadscharts = ({nextFollowUps,leadsFronWebsites,leadsFronLinkedin,leadsFronInstagram,leadsFronOthers,leadsFronFacebook,  leadConverted, leadLost, totalLeads }) => {
  const navigate = useNavigate();


  return (
    <div style={{ background: "#1f1f1f" }} className="">
      <Row >
        <Col style={{ background: "#F1F1FA" }}>
          <div style={{ fontWeight: '700', fontSize: "1.5rem", lineHeight:"28px", fontStyle:'normal'}} className="pt-5 ">
            All Leads
          </div>
          <div style={{ color: "#64676B", fontWeight: "400", fontSize:'18px' }} className="pb-3">
            Leads Generated Overview
          </div>
        </Col>
        <Col className="pt-5" style={{ background: "#F1F1FA" }}>
          <Button onClick={() => navigate("/add-lead")}
            style={{ background: "#176EB3", float: "right" }}
          >
            Add New Lead +
                </Button>
        </Col>
      </Row>
      
      <Row  style={{ background: "#fff" }}>
        <Col md={4} className='' style={{padding:'0 16px'}}>
          <div style={{ fontWeight: "700", fontSize: "22px" }} className="pt-3">
            Leads generated by you
          </div>
          <Row className="mt-2"  style={{ width: "auto" , padding:"0 5px"}}>
            <Col md={6} className="">
              <div
                style={{
                  width: "auto",
                  borderRadius: "",
                  background: "#fff",
                  border:'2px solid #DD2A7B'
              
                }}
                className=" d-flex flex-column align-items-center  justify-content-center p-3"
              >
                <div className="d-flex justify-content-center">
                  <div
                    style={{
                      height: "40px",
                      width: "40px",
                      borderRadius: "50px",
                      background: "#DD2A7B",
                      fontWeight: "700",
                      color: "#fff",
                      fontSize: "20px",
                    }}
                    className="d-flex justify-content-center align-items-center"
                  >
                    <img src="/images/dashboard/newleads.png" alt="thailo" className="img-fluid" style={{ height: "20px", width: "20px" }} />
                  </div>
                </div>
                <div
                  style={{
                    paddingTop: "10px",
                    fontWeight: "700",
                    fontSize: "30px",
                  }}
                  className="d-flex justify-content-center"
                >
                  {totalLeads}
                </div>

                <div
                  style={{ color: "#64676B"  }}
                  className="d-flex justify-content-center"
                >
                  New Leads
                  </div>
              </div>
            </Col>
            <Col md={6} className="pb-4">
              <div
                style={{
                  borderRadius: "",
                  background: "#FEE8F2",
                }}
                className="  d-flex flex-column align-items-center  justify-content-center p-3 "
              >
                <div className="d-flex justify-content-center">
                  <div
                    style={{
                      height: "40px",
                      width: "40px",
                      borderRadius: "50px",
                      background: "#DD2A7B",
                      fontWeight: "700",
                      color: "#fff",
                      fontSize: "20px",
                    }}
                    className="d-flex justify-content-center align-items-center"
                  >
                    <img src="/images/dashboard/converted.png" alt="thailo" className="img-fluid" />
                  </div>
                </div>
                <div
                  style={{
                    paddingTop: "10px",
                    fontWeight: "700",
                    fontSize: "30px",
                  }}
                  className="d-flex justify-content-center"
                >
                  {nextFollowUps}
                </div>

                <div
                  style={{ color: "#64676B" }}
                  className="d-flex justify-content-center"
                >
                  In follow Up
                  </div>
              </div>
            </Col>
            <Col md={6} className="pb-4">
              <div
                style={{
                  borderRadius: "",
                  background: "#FEE8F2",
                }}
                className=" d-flex flex-column align-items-center  justify-content-center p-3 "
              >
                <div className="d-flex justify-content-center">
                  <div
                    style={{
                      height: "40px",
                      width: "40px",
                      borderRadius: "50px",
                      background: "#DD2A7B",
                      fontWeight: "700",
                      color: "#fff",
                      fontSize: "20px",
                    }}
                    className="d-flex justify-content-center align-items-center"
                  >
                    <img src="/images/dashboard/followup.png" alt="thailo" className="img-fluid" />
                  </div>
                </div>
                <div
                  style={{
                    paddingTop: "10px",
                    fontWeight: "700",
                    fontSize: "30px",
                  }}
                  className="d-flex justify-content-center"
                >
                  {leadConverted}
                </div>

                <div
                  style={{ color: "#64676B" }}
                  className="d-flex justify-content-center"
                >
                  Lead Converted
                  </div>
              </div>
            </Col>
            <Col md={6} className="pb-4">
              <div
                style={{
                  borderRadius: "",
                  background: "#FEE8F2",
                }}
                className="  d-flex flex-column align-items-center  justify-content-center p-3 "
              >
                <div className="d-flex justify-content-center">
                  <div
                    style={{
                      height: "40px",
                      width: "40px",
                      borderRadius: "50px",
                      background: "#DD2A7B",
                      fontWeight: "700",
                      color: "#fff",
                      fontSize: "20px",
                    }}
                    className="d-flex justify-content-center align-items-center"
                  >
                    <img src="/images/dashboard/lost.png" alt="thailo" className="img-fluid" />
                  </div>
                </div>
                <div
                  style={{
                    paddingTop: "10px",
                    fontWeight: "700",
                    fontSize: "30px",
                  }}
                  className="d-flex justify-content-center"
                >
                  {leadLost}
                </div>

                <div
                  style={{ color: "#64676B" }}
                  className="d-flex justify-content-center"
                >
                  Lead Lost
                  </div>
              </div>
            </Col>
          </Row>
        </Col>
        
        <Col md={4}  >
        <div className= 'leadcharts' style={{height:'52vh', background:'#FFF',padding:'.5rem 1rem'}}>

        <div className="pt-3" style={{ fontWeight: "700", fontSize: "1.2rem" , }}>Leads Stats</div>
        <div className='d-flex justify-content-center barchart ' style={{height:"35vh ", width:'90%'}}>
        <BarChart />

        </div>

                  <div style={{ fontWeight: "700", fontSize: "1.2rem" }} className='d-flex justify-content-center align-items-center pt-4 leadchartt '>Total Leads: {totalLeads}</div>

        </div>
        </Col>
        <Col  md={4} className="mt-5" style={{ }}>
        <Stack className="px-3 " style={{}}>
              <span
                // className="m-0"
                style={{
                  fontFamily: "arial",
                  fontWeight: "400",
                  fontSize: "17px",
                  lineHeight: "19.55px",
                }}
              >
                Website:
              </span>
              <div className="d-flex">
                <Col className="pe-1">
                  <ProgressBar
                    now={leadsFronWebsites/totalLeads*100}
                    style={{
                      background: "#B8AAEE",
                      marginBottom:"3.5vh"
                      // height:'5px',
                      // width:'100%'

                      // backgroundColor: "#B8AAEE",
                    }}
                  />
                </Col>
                <div>
                  <span
                    className="flex-shrink-1"
                    style={{
                      fontFamily: "Arial",
                      fontStyle: "normal",
                      fontWeight: "normal",
                      fontSize: "17px",
                      lineHeight: "20px",
                      textAlign: "right",
                    }}
                  >
                    {leadsFronWebsites/totalLeads*100}
                  </span>
                </div>
              </div>
              <span
                // className="m-0"
                style={{
                  fontFamily: "arial",
                  fontWeight: "400",
                  fontSize: "17px",
                  lineHeight: "19.55px",
                }}
              >
                Linkedin:
              </span>
              <div className="d-flex">
                <Col className="pe-1">
                  <ProgressBar
                    now={leadsFronLinkedin/totalLeads*100}
                    variant="danger"
                    style={{ background: "#F9AAA7",                      marginBottom:"3.5vh"
                  }}
                  />
                </Col>
                <div>
                  <span
                    className="flex-shrink-1"
                    style={{
                      fontFamily: "Arial",
                      fontStyle: "normal",
                      fontWeight: "normal",
                      fontSize: "17px",
                      lineHeight: "20px",
                      textAlign: "right",
                    }}
                  >
                    {leadsFronLinkedin/totalLeads*100}
                  </span>
                </div>
              </div>{" "}
              <span
                // className="m-0"
                style={{
                  fontFamily: "arial",
                  fontWeight: "400",
                  fontSize: "17px",
                  lineHeight: "19.55px",
                }}
              >
                Facebook:
              </span>
              <div className="d-flex">
                <Col className="pe-1">
                  <ProgressBar
                    now={leadsFronFacebook/totalLeads*100}
                    variant="warning"
                    style={{ background: "#F2E3B5",                      marginBottom:"3.5vh"
                  }}
                  />
                </Col>
                <div>
                  <span
                    className="flex-shrink-1"
                    style={{
                      fontFamily: "Arial",
                      fontStyle: "normal",
                      fontWeight: "normal",
                      fontSize: "17px",
                      lineHeight: "20px",
                      textAlign: "right",
                    }}
                  >
                    {leadsFronFacebook/totalLeads*100}
                  </span>
                </div>
              </div>{" "}
              <span
                // className="m-0"
                style={{
                  fontFamily: "arial",
                  fontWeight: "400",
                  fontSize: "17px",
                  lineHeight: "19.55px",
                }}
              >
                Instagram:
              </span>
              <div className="d-flex">
                <Col className="pe-1">
                  <ProgressBar
                    now={leadsFronInstagram/totalLeads*100}
                    variant="info"
                    style={{ background: "#EBF9FF",                      marginBottom:"3.5vh"
                  }}
                  />
                </Col>
                <div>
                  <span
                    className="flex-shrink-1"
                    style={{
                      fontFamily: "Arial",
                      fontStyle: "normal",
                      fontWeight: "normal",
                      fontSize: "17px",
                      lineHeight: "20px",
                      textAlign: "right",
                    }}
                  >
                                        {leadsFronInstagram/totalLeads*100}

                  </span>
                </div>
              </div>{" "}
              <span
                // className="m-0"
                style={{
                  fontFamily: "arial",
                  fontWeight: "400",
                  fontSize: "17px",
                  lineHeight: "19.55px",
                }}
              >
                Others:
              </span>
              <div className="d-flex">
                <Col className="pe-1">
                  <ProgressBar
                    now={leadsFronOthers/totalLeads*100}
                    variant="success"
                    style={{ background: "#70E765",                      marginBottom:"3.5vh"
                  }}
                  />
                </Col>
                <div>
                  <span
                    className="flex-shrink-1"
                    style={{
                      fontFamily: "Arial",
                      fontStyle: "normal",
                      fontWeight: "normal",
                      fontSize: "17px",
                      lineHeight: "20px",
                      textAlign: "right",
                    }}
                  >
                    {leadsFronOthers/totalLeads*100}
                  </span>
                </div>
              </div>
              <strong style={{ textAlign: "center", fontSize:'20px', fontWeight:'700' }}>Lead Source</strong>
            </Stack>
        </Col>
      </Row>
      
    </div>
  );
};

export default Leadscharts;
